spring:
  application:
    name: fawry-lms
  datasource:
    url: "jdbc:postgresql://localhost:5432/fawry_lms"
    username: "postgres"
    password: "postgres"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true